name: Publish Stable Image
on:
  push:
    tags:
      - '*'
jobs:
  build-stable-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD         
      - name: Docker Build Image
        run: |
          DOCKER_BUILDKIT=1 docker build . -t epsilonis/schoolsgo-web:${{  github.ref_name }}
      - name: Publish Docker Image
        run: |
          docker push epsilonis/schoolsgo-web:${{  github.ref_name }}
          docker system prune -f -a